cursor #1d1a22
cursor_text_color #494453

foreground            #1d1a22
background            #fef7ff
selection_foreground  #ffffff
selection_background  #cfbef6
url_color             #39008b

color0   #15121a
color1   #840019
color2   #006817
color3   #a67b00
color4   #3b0091
color5   #c7a7f6
color6   #39008b
color7   #252326
color8   #727076
color9   #cd363a
color10  #009822
color11  #b48600
color12  #8a4ae3
color13  #c7a7f6
color14  #7f5ab4
color15  #cbc8d0
