# ============================================================
# THEME — Catppuccin
# ============================================================

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "default"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g status-style "bg=default"

setw -g pane-border-status off
setw -g pane-border-lines single
setw -g pane-active-border-style "bg=default,fg=#{@thm_overlay_0}"
setw -g pane-border-style "bg=default,fg=#{@thm_surface_0}"
